version: '3.8'
services:
  app:
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "8000:80"
      - "5005:5005"
      - "80:80"
    volumes:
      - ./nginx/builvderse-app.conf:/etc/nginx/conf.d/buildverse-app.conf
    networks:
      - web_network
    depends_on: 
      - app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
